language: objective-c
osx_image: xcode7.3

before_install:
    - env
    - locale
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
	- pod --version
	- xcpretty --version
	- xcodebuild -version
	- xcodebuild -showsdks